services:
  db:
    env_file:
      - .env
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    networks:
      - app-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     GEMINI_API_KEY: ${GEMINI_API_KEY}
  #   depends_on:
  #     - db
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./src:/app/src
  #   networks:
  #     - app-network
  #   command: sh -c "sleep 10 && node dist/src/main.js"

networks:
  app-network:
    driver: bridge
